export JAVA_HOME=`/usr/libexec/java_home`
PLAY_HOME=~/dev/env/play
#export M2_HOME=/opt/apache/maven
#export ANT_HOME=/opt/apache/ant

export PATH=$PATH:$JAVA_HOME/bin
#export PATH=$PATH:$M2_HOME/bin
#export PATH=$PATH:$ANT_HOME/bin

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting

PATH=$PATH:/usr/local/share/npm/bin # npm binaries
PATH=$PATH:$PLAY_HOME

ulimit -n 10000 # set max number of open files. In OS X this limit is set to 256 by default, which is very low

source /Users/ivan/.rvm/scripts/rvm
